services:
  postgres:
    image: postgres:15
    container_name: employee-postgres

    environment:
      POSTGRES_DB: employeedb
      POSTGRES_USER: employeeuser
      POSTGRES_PASSWORD: employeepass
      TZ: UTC
    ports:
      - "5454:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
